### ISSUE TITLE
use local DocumentDB instance for testing

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/documentdb-session#35]

**Comment by danzel** [comment]
I'm trying this at the moment, and it doesn't like the self signed cert

![image](https://cloud.githubusercontent.com/assets/393086/20693158/593b51e4-b641-11e6-95f1-b198fe9a4e85.png)

**Comment by danzel** [comment]
Worked around by setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` in code (less than ideal but works for dev)
